version: "3.3"
services:
  microservice:
    build:
      "./"
    container_name: localizacao-ms
    networks:
      - autenticacao
    ports:
      - "8081:8081"

networks:
  autenticacao:
    external: true